Add events for tracking state of the Removal contract
nori-dot-eco/contracts pull request #325
Opened 2022-08-01 19:48 UTC by rlfarman

2022-08-01 19:53 UTC, jaycenhorton requested changes
can you check in the updated forge snapshot?

2022-08-02 16:19 UTC, scottynomad requested changes
@rlfarman I feel like this is suffering some of the same issues I pointed out with the market events yesterday -- while we want to emit events on state changes, the granularity at which we do so should map more onto the external interface of the contract rather that onto the individual implementation details of the internal data structures.

i.e. I would expect only one event per removal minted in the `mintBatch` function.  One to say that a schedule was created.

My instinct would also be to omit the balance updated one since that's state we're rolling up internally for efficiency sake only -- however I know Jaycen is concerned about that getting out of sync and this is the only way we'd know if it did so probably smart to keep it in.

2022-08-05 22:32 UTC, jaycenhorton commented on .gas-snapshot
> +Certificate**msgSenderERC721A:test() (gas: 354)
fyi i think something got messed up in this file-- can you regenerate it before merging?

2022-08-05 22:33 UTC, jaycenhorton commented on contracts/Removal.sol
> +    address indexed releasedFrom,
naming feels redundant given the name of the event, perhaps change to `from`, `account` `owner` `supplier` or something like that

2022-08-05 22:33 UTC, jaycenhorton commented on contracts/Removal.sol
> +    uint256 indexed removalId,
naming feels redundant given the name of the event, perhaps change to `id` `removal` or something similar

2022-08-05 22:36 UTC, jaycenhorton commented on contracts/Removal.sol
> +        this.certificateAddress(),
using `address(_certificate)` _may_ make this cheaper

2022-08-05 22:36 UTC, jaycenhorton commented on contracts/Removal.sol
> +    emit RemovalReleased(removalId, this.marketAddress(), amount);
using `address(_market)` _may_ make this cheaper

2022-08-09 14:47 UTC, amiecorso commented on contracts/Removal.sol
> +   * @notice Emitted on updating `_removalIdToRemovalData` with a new removal.
fix comment ^

2022-08-09 14:54 UTC, amiecorso approved these changes
just a copy paste typo in the event docs, otherwise looks good. realizing we may rewrite `mintBatch` to customize our minting event behavior and that that would come in a separate PR

2022-08-09 21:34 UTC, merged