Add swap functionality without fees for market admins
nori-dot-eco/contracts pull request #439
Opened 2022-11-21 22:02 UTC by rlfarman

Adds two new external functions, `swapWithoutFee` and `swapFromSupplierWithoutFee` to the Market contract. These are restricted to the `MARKET_ADMIN_ROLE`.

Extracts the shared logic from both versions of `swap` and `swapFromSupplier` functions to two new internal functions, `_prepareSwap` and `_prepareSwapWithoutFee` to keep it DRY.

Added tests for purchasing multiple removals using the without fees.

2022-11-22 17:32 UTC, jaycenhorton commented on contracts/Market.sol
> +    ) = _prepareSwap(certificateAmount, deadline, v, r, s);
Use named params

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param v The recovery identifier for the permit's secp256k1 signature
```suggestion
   * @param v The recovery identifier for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param r The r value for the permit's secp256k1 signature
```suggestion
   * @param r The r value for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param s The s value for the permit's secp256k1 signature
```suggestion
   * @param s The s value for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param v The recovery identifier for the permit's secp256k1 signature
```suggestion
   * @param v The recovery identifier for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param r The r value for the permit's secp256k1 signature
```suggestion
   * @param r The r value for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param s The s value for the permit's secp256k1 signature
```suggestion
   * @param s The s value for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @notice Prepares an order to be fulfilled.
```suggestion
   * @notice Prepare an order to be fulfilled.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +      certificateAmount
Use named param

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param v The recovery identifier for the permit's secp256k1 signature
```suggestion
   * @param v The recovery identifier for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param r The r value for the permit's secp256k1 signature
```suggestion
   * @param r The r value for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param s The s value for the permit's secp256k1 signature
```suggestion
   * @param s The s value for the permit's secp256k1 signature.
```

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +          (unrestrictedSupplierFee * holdbackPercentage) /
You can use muldiv by openzepelin here to improve gas efficiency

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +        certificateAmount,
Use named params

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +    ) = _prepareSwap(amount, deadline, v, r, s);
Use named param

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +    ) = _prepareSwapFromSupplier(amount, supplier, deadline, v, r, s);
Use named params

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +    address operator,
Is it possible to rename this to `from`? `operator` typically means the address which is an approved spender of the tokens, but this looks like it's using `from: operator` yet operator == `msg.sender` which is confusing (and potentially a misuse of operator params if it's actually relying on msg.sender being the operator somewhere-- which I didn't see but maybe i didn't look close enough)

2022-11-22 17:46 UTC, jaycenhorton commented on contracts/Market.sol
> +   * @param operator The message sender.
```suggestion
   * @param operator The address to transfer bpNori from.
```
Or something along those lines

2022-11-29 23:01 UTC, rlfarman commented on contracts/Market.sol
> -  /**
Moved this to fix eslint errors

2022-11-29 23:02 UTC, rlfarman commented on contracts/Market.sol
> -    uint256 availableSupply = _removal.getMarketBalance();
Moved to `_allocateRemovals`

2022-11-29 23:02 UTC, rlfarman commented on contracts/Market.sol
> -    _purchasingToken.permit({
Moved to `_permit`

2022-11-29 23:02 UTC, rlfarman commented on contracts/Market.sol
> +   * IERC20WithPermit tokens for an ERC721 certificate token and transfers ownership of removal tokens supplied only
Fixed eslint errors with this docstring

2022-11-29 23:04 UTC, rlfarman commented on contracts/Market.sol
> -   * @notice Calculates the total quantity of ERC20 tokens required to make a purchase of the specified `amount` (in tonnes of
Fixed eslint errors and added @return arg name for this function

2022-11-29 23:04 UTC, rlfarman commented on contracts/Market.sol
> +  /**
Moved from above

2022-12-01 17:58 UTC, amiecorso commented on contracts/Market.sol
> +   * @notice Exchange bpNORI tokens for an ERC721 certificate by transferring ownership of the removals to the
```suggestion
   * @notice Exchange ERC20 tokens for an ERC721 certificate by transferring ownership of the removals to the
```

2022-12-01 17:59 UTC, amiecorso commented on contracts/Market.sol
> +   * to transfer the sender's bpNORI to complete the purchase. A certificate is minted in the Certificate contract
```suggestion
   * to transfer the sender's ERC20 to complete the purchase. A certificate is minted in the Certificate contract
```

2022-12-01 18:01 UTC, amiecorso commented on contracts/Market.sol
> +   * @notice An overloaded version of `swap` that additionally accepts a supplier address and will exchange bpNORI
same notes on the presence of "bpNori" in this docstring

2022-12-01 18:04 UTC, amiecorso commented on contracts/Market.sol
> +   * purchased and the fee paid to Nori.
```suggestion
   * purchased and any fees paid to Nori.
```

2022-12-01 18:07 UTC, amiecorso commented on test/checkout.int.t.sol
> -
why is all of this code being deleted?  it looks like my tests that test purchases using an alternate ERC20 are also deleted from this file?

2022-12-01 18:09 UTC, amiecorso requested changes
looking good! nice refactor of some of our market functions.  just some comments mainly on docstring stuff and then it looks like some tests were deleted that I'd rather be kept in?

2022-12-02 16:09 UTC, amiecorso approved these changes

2022-12-02 18:16 UTC, merged